// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from 'controllers/application'

import ArtistsSongsController from './artists_songs_controller'
application.register('artists-songs', ArtistsSongsController)
