version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails-lyrics-site
      - bundle:/usr/local/bundle
      - tmp-data:/rails-lyrics-site/tmp
      - public-data:/rails-lyrics-site/public
    ports:
      - "3000:3000"
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
    depends_on:
      - db
      - redis
      - elasticsearch

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/rails-lyrics-site
    depends_on:
      - db
      - redis
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - ELASTIC_PASSWORD=sVUurmsWYEwnliUxp3pX
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - search-data:/usr/share/elasticsearch/data

  logstash:
    image: logstash:7.10.1
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ls-data:/usr/share/logstash/data
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.10.1
    ports:
      - "5601:5601"
    volumes:
      - kb-data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_USERNAME="kibana_system"
      - ELASTICSEARCH_PASSWORD="sVUurmsWYEwnliUxp3pX"
    depends_on:
      - elasticsearch

volumes:
  bundle:
  tmp-data:
  public-data:
  search-data:
  ls-data:
  kb-data:
