name: Download Test Coverage Result
on: [pull_request]

jobs:
  download-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download object
        uses: aws-actions/s3-download@v1
        env:
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: ap-northeast-1
          BUCKET: demo-code-coverage
          OBJECT: /coverage
          OUTPUT_FILE: ./coverage
